AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0f6fe3c5b0f246063 #change the ImageID
      InstanceType: 't3.micro' #change the type
      SecurityGroupIds:
        - 'sg-xxxxxxxxxx'  #write your Security Group ID
      UserData: #Website
        Fn::Base64: !Sub |
          #!/bin/bash
          echo "Hello Hiba Iam EC2" > /var/www/html/index.html
          yum install -y httpd
          service httpd start
          chkconfig httpd on
